FROM node:18
RUN apt-get update && apt-get install libvips-dev -y
RUN npm install -g npm@6
ARG NODE_ENV=production
WORKDIR /opt/
COPY ./package.json ./package-lock.json ./
ENV PATH /opt/node_modules/.bin:$PATH
RUN npm install
WORKDIR /opt/app
COPY ./ .
RUN npm run build
EXPOSE 1337
CMD [ "npm", "run", "start"]